import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { GetStaticProps } from 'next';
import Link from 'next/link';
import Image from 'next/image';
import fs from 'fs';
import path from 'path';

interface People {
  id: string;
  name: string;
  relatedPersonId: string;
}

interface Detail {
  id: string;
  age: number;
  address: string;
  relatedPeople: Array<{ id: string; relation: string }>;
}

interface HomeProps {
  people: People[];
  details: Detail[];
}

export const getStaticProps: GetStaticProps<HomeProps> = async () => {
  const peopleFilePath = path.join(process.cwd(), 'public', 'people.json');
  const peopleJsonData = fs.readFileSync(peopleFilePath, 'utf8');
  const people: People[] = JSON.parse(peopleJsonData);

  const detailsFilePath = path.join(process.cwd(), 'public', 'details.json');
  const detailsJsonData = fs.readFileSync(detailsFilePath, 'utf8');
  const details: Detail[] = JSON.parse(detailsJsonData);

  return {
    props: {
      people,
      details,
    },
  };
};

const Home: NextPage<HomeProps> = ({ people, details }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Next.js on Replit!
        </h1>

        <p className={styles.description}>
          List of people:
        </p>

        <ul>
          {people.map((person) => (
            <li key={person.id}>
              <Link href={`/people/${person.id}`}>{person.name}</Link>
            </li>
          ))}
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="/__repl"
          target="_blank"
          rel="noopener noreferrer"
        >
          Built on
          <span className={styles.logo}>
            <Image src="/replit.svg" alt="Replit Logo" width={20} height={18} objectFit="contain" />
          </span>
          Replit
        </a>
      </footer>
    </div>
  );
};

export default Home;
